In [1]:
print("Hello, World!")

Hello, World!


This is where all our imports go:

In [2]:
import numpy as np

Let's create an array:

In [3]:
x = np.array([1, 2, 3])

In [4]:
x

array([1, 2, 3])

In [5]:
print(x)

[1 2 3]


In [6]:
# reassigning x
x = np.array([4, 5, 6])

In [7]:
x

array([4, 5, 6])